<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad020a0c706572736f6e2e70726f746f121a50726f746f62756642656e" .
            "63686d61726b732e4d65737361676522f8010a06506572736f6e120c0a04" .
            "6e616d65180120012809120a0a026964180220012805120d0a05656d6169" .
            "6c180320012809123d0a0570686f6e6518042003280b322e2e50726f746f" .
            "62756642656e63686d61726b732e4d6573736167652e506572736f6e2e50" .
            "686f6e654e756d6265721a590a0b50686f6e654e756d626572120e0a066e" .
            "756d626572180120012809123a0a047479706518022001280e322c2e5072" .
            "6f746f62756642656e63686d61726b732e4d6573736167652e506572736f" .
            "6e2e50686f6e6554797065222b0a0950686f6e6554797065120a0a064d4f" .
            "42494c45100012080a04484f4d45100112080a04574f524b100262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

